version: "3.8"
services:
  web:
    image: node:14.10.1
    tty: true
#    command: npm run dev
    volumes:
      - ./app:/app
    ports:
      - "${PORT}:${PORT}"
    working_dir: /app
    env_file: .env
